name: todos_by_bloc
description: "Demo project about Todo list, State mangement by BLoC pattern."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  provider: ^6.1.2
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

  # API & Environment
  dio: ^5.4.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  flutter_dotenv: ^5.1.0
  http: any

  # Service
  easy_localization: ^3.0.5
  equatable: ^2.0.5
  logger: ^2.2.0
  package_info_plus: ^6.0.0
  path_provider: ^2.1.2
  rxdart: ^0.27.7

  # DB or Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # UI
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  json_annotation: ^4.8.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app-bg.jpeg"
  android_12:
    image: "assets/images/app-bg.jpeg"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleToFill
  fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/locales/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
