// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseProdOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // FirebaseOptions and keys config here..
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7pZwsSWb0FT1AVYIw1UKJ_cpq2l6FU6c',
    appId: '1:1066097970733:android:760f2a7f130c15349c32a4',
    messagingSenderId: '1066097970733',
    projectId: 'ecommerce-todos-app-ca7b7',
    storageBucket: 'ecommerce-todos-app-ca7b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0O4YT8KSR3g5RJKlByr9kL7NRwovR5pA',
    appId: '1:1066097970733:ios:6868dac7a773014d9c32a4',
    messagingSenderId: '1066097970733',
    projectId: 'ecommerce-todos-app-ca7b7',
    storageBucket: 'ecommerce-todos-app-ca7b7.appspot.com',
    iosClientId: '1066097970733-li6e723sh9v1ulv86aiu5qqcjipv4gc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todosByBloc',
  );
}
